### ISSUE TITLE
Bug Dracula Theme When Running Full Reload

### ISSUE THREAD

**Issue by lucasfernandodev** [dracula/hyper#13]
![Capturar](https://user-images.githubusercontent.com/20525486/67050733-a36ace00-f10f-11e9-8e36-db735b742d37.PNG)

Hyper is bugging every time I run full reload, the program blurs the edges of the dracula theme and it is necessary to close the program to get it back to normal.

**Comment by dangvanthanh** [comment]
Hi @LucasFernandoWeb 

On Windows 10, you need configuring bash as default shell.

In `.hyper.js`, you want to to find this section

```shell
// - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
shell: '',
```

Let's change that to

```shell
// - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
shell: 'C:\\Ruby23-x64\\devkit\\bin\\bash.exe',
```

You can find path folder by this command line, assume your os installed bash

```shell
$ where bash
```

Example screenshot

![hyper-on-windows-10](https://user-images.githubusercontent.com/2674850/77499911-05312000-6e86-11ea-9377-72fc5e740cb9.png)
