### ISSUE TITLE
Dracula Theme dont work with plugin hyperpower

### ISSUE THREAD

**Issue by hazkall** [dracula/hyper#16]
>Dracula Theme dont work with hyperpower plugin

>Follow hyper.js file with plugins attached.

plugins: [
    "hyper-dracula",
    "hyper-custom-controls",
    "hyper-hide-scroll",
    "hyper-font-ligatures",
    "hyper-active-tab",
    "hyperterm-tabs",
    "hyper-blink",
    "space-pull",
    "gitrocket"]

**Comment by dangvanthanh** [comment]
Hi @lipenodias 

Thank you very much when you report the issue.

The issue was fixed in #15 but I missing release the new version.

You now reload the plugin and see it working with `hyperpower`

**Comment by hazkall** [comment]
ty for the support! :)

**Comment by dangvanthanh** [comment]
Your welcome @lipenodias
