### ISSUE TITLE
Submit to Dracula Theme organization

### ISSUE THREAD

**Issue by benreyn** [dracula/hyper#2]
Would love to see this incorporated into [`dracula-theme`](https://github.com/dracula/dracula-theme), so it can be a part of the larger dracula theme community and featured on https://draculatheme.com.

@dangvanthanh Thoughts?

**Comment by dangvanthanh** [comment]
@benjamreynolds I'm very honoured my theme can be incorporated into [dracula-theme](https://draculatheme.com/). How I submit to dracula theme organization?

**Comment by benreyn** [comment]
Check out https://github.com/dracula/dracula-theme/#how-do-i-submit-a-new-theme

**Comment by benreyn** [comment]
Looks like actually theres already some discussion that seemed to fizzle out in dracula/dracula-theme#202. maybe chime in there and see what the status of things is.

**Comment by dangvanthanh** [comment]
I will keep follow status this theme [ dracula/dracula-theme](https://github.com/dracula/dracula-theme/issues/202). Thank you very much.

**Comment by zenorocha** [comment]
I added you to the organization. Once you accept it, you should be able to transfer the repository.

Once you do, I need you to rename it to `hyper-dracula` and update the readme file to follow the template: https://github.com/dracula/template.

**Comment by dangvanthanh** [comment]
@zenorocha I'm update to `hyper-dracula`

**Comment by zenorocha** [comment]
Nice! I think we have all we needed. Can you transfer the repository to the `dracula` org now?

**Comment by dangvanthanh** [comment]
I was transfer to `dracula` org.

**Comment by zenorocha** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 

Repository transferred and renamed!
https://github.com/dracula/hyper

npm package transferred and republished!
https://www.npmjs.com/package/hyper-dracula

I have some colors changes that I want to send you, but I'll probably only have time to send it during the weekend.

Thanks @dangvanthanh for your hard work!

**Comment by BerkeleyTrue** [comment]
Was the old npm package deleted?

**Comment by zenorocha** [comment]
No, we published a new repository on top of it.

**Comment by BerkeleyTrue** [comment]
The old npm package has been deleted https://www.npmjs.com/package/hyper-dark-dracula

Hyper (or npm) doesn't have a nice way of letting you know that a package has been removed. 

After a bit of googling I found that this repo used to be the old one.

Usually removing packages from npm is seen as potentially damaging (read: leftpad). Just add a deprecation notice and point to the new package/repo. Not that there is anything that can be done now (unless the package can be restored).

**Comment by zenorocha** [comment]
Looks like the package was deprecated, not removed. Can you confirm @dangvanthanh?

**Comment by BerkeleyTrue** [comment]
This is the result if trying to use the previous npm package on hyper load. 

![developer_tools_-_file____applications_hyper_app_contents_resources_app_index_html](https://cloud.githubusercontent.com/assets/6775919/25059050/1f4e6e08-2135-11e7-805f-50eab24ff34b.png)

**Comment by dangvanthanh** [comment]
@BerkeleyTrue This old plugin `hyper-dark-dracula` I was deleted on npmjs. Now you only can use [hyper-dracula](https://www.npmjs.com/package/hyper-dracula)

**Comment by BerkeleyTrue** [comment]
@dangvanthanh I'm aware of that.

How do you communicate that to users who are not aware of the package name change if you have deleted the old package?

**Comment by dangvanthanh** [comment]
I'm sorry I didn't notice. I should to give you all changes before I deleted the old package. I'm sorry about that. Thank you very much @BerkeleyTrue I will find solution to be aware all of users I was change `hyper-dark-dracula` to `hyper-dracula`

**Comment by zenorocha** [comment]
Shouldn't Hyper detect packages marked as deprecated and show some message?

**Comment by dangvanthanh** [comment]
I think when users open `hyper` I will notice for change `hyper-dark-dracula` to `hyper-dracula`
