### ISSUE TITLE
Is it possible to change only `backgroundColor` in Hyper, e.g., black?

### ISSUE THREAD

**Issue by sehilyi** [dracula/hyper#22]
Thanks for this theme!

I was wondering if it's possible to change the background color, but use all other Dracula colors, for my Hyper terminal.

**Comment by dangvanthanh** [comment]
Sure @sehilyi 

I will write options for you can override background in Hyper with this plugins

**Comment by thanhdangdg** [comment]
@sehilyi 

From `v0.2.2`, you can override background color in Hyper. Edit ``~/.hyper.js`

```shell
module.exports = {
  config: {
    backgroundColor: '#32302f' // override background color
  },
  plugins: {
    'hyper-dracula'
  }
}
```

**Comment by dangvanthanh** [comment]
@sehilyi 

From `v0.2.2`, you can override background color in Hyper. Edit `~/.hyper.js`

```shell
module.exports = {
  config: {
    backgroundColor: '#32302f' // override background color
  },
  plugins: {
    'hyper-dracula'
  }
}
```
