### ISSUE TITLE
Command seems incorrect on webpage

### ISSUE THREAD

**Issue by Kush131** [dracula/hyper#3]
Hello!

When trying to install Dracula I ran into some issues installing. It seems that the webpage suggests using "hpm install hyper-dracula" when there is no package by that name. Is this a typo? There seems to be a hyperterm-dracula package that exists, but it doesn't seem to match the theme that is on the webpage. If you install via npm (where a hyper-dracula package does exist) the install seems to work.

Thanks!

**Comment by gricelsepulveda** [comment]
I have the same issue. I installed it and I checked the .hyper.js file and dracula-theme is set between plugins brackets, but the colors doesn't seem to match to the dracula's theme u.u

**Comment by dangvanthanh** [comment]
Hi @Kush131 
Hi @gricelsepulveda 

I owner **hyperterm-dracula** package before but when joined to [Dracula Theme Team](https://github.com/dracula) I was deleted from npm.js. This is my fault.

Now, if you use [hpm-cli](https://github.com/zeit/hpm) you can find **hyper-dracula** package. I will report to hpm-cli team.

You can add **hyper-dracula** to the plugins list in your `~/.hyper.js` config file.

```js
plugins: [
	"hyper-dracula"
]
```
