### ISSUE TITLE
Shell used in the preview image

### ISSUE THREAD

**Issue by victorronnow** [dracula/hyper#4]
Hey!
Just wanted to know what shell you were using (the one shown on the preview image). Is it a custom zsh shell?

**Comment by zacharyrs** [comment]
I think it might be https://github.com/sindresorhus/pure
At least that's what I'm using now...

**Comment by dangvanthanh** [comment]
Hi @victorronnow 

I using [Oh My Zsh](https://github.com/robbyrussell/oh-my-zsh) and [Pure Theme](https://github.com/sindresorhus/pure) (change name to **refined**) as @zacharyrs said.

**Comment by zacharyrs** [comment]
Changed name to refined?

**Comment by dangvanthanh** [comment]
Yes. When you config theme in zsh you will see notification such as below.

![Refined](https://user-images.githubusercontent.com/2674850/28875346-783e598e-77bf-11e7-98d5-b249b8e92339.png)

**Comment by zacharyrs** [comment]
Oh I see, it's a different build of pure.

You're using the pure (now refined) bundled in Oh My ZSH, whereas I run the [original](https://github.com/sindresorhus/pure) version.
