### ISSUE TITLE
Bash prompt not changing

### ISSUE THREAD

**Issue by swthate** [dracula/hyper#5]
Hi, all.

I'm using bash in Hyper and after activating (and restarting, and full reloading) the Dracula theme the prompt doesn't change colors, it keeps the same ugly magenta/orange colors (see attached 1). However, if I run something like `git status`, then I can see the good old Dracula colors coming through (see attached 2).

UPDATE

There IS a bash profile lurking in my home directory that is changing the default bash prompt. [Here's a gist](https://gist.github.com/swthate/a0f3fea630bdae8dfa431fda1d87db1b) of the profile I grabbed who knows when! However, when I remove that profile the bash prompt reverts to the plain, boring white prompt (see attached 3).

Thanks!

(1)

![screen shot 2017-09-15 at 10 05 01 am](https://user-images.githubusercontent.com/4054580/30489811-e012550a-99fd-11e7-8209-5a405c101db2.png)

(2)

![screen shot 2017-09-15 at 10 07 37 am](https://user-images.githubusercontent.com/4054580/30489818-e3a0a474-99fd-11e7-8b7d-71e53e65c58d.png)

(3)

![screen shot 2017-09-15 at 10 17 39 am](https://user-images.githubusercontent.com/4054580/30490283-1f5bf9d6-99ff-11e7-8fcb-8c31a3f0a6c2.png)

**Comment by ghost** [comment]
@swthate - Your bash profile is setting colors for the prompt based on Solarized, specifically lines 15 through 19. I had a similar setup in my dotfiles. I ditched the conditional and just set the colors based on whatever theme I have selected at the time:

```sh
local reset=""
local black=""
local red=""
local green=""
local yellow=""
local blue=""
local purple=""
local cyan=""
local white=""

reset="\e[0m"
black="\e[1;30m"
red="\e[1;31m"
green="\e[1;32m"
yellow="\e[1;33m"
blue="\e[1;34m"
purple="\e[1;35m"
cyan="\e[1;36m"
white="\e[1;37m"
```
